# -*- coding: utf-8 -*-
"""Yeast AutoOligo CRISPR Helper 1.03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1G1eY4AUthsGDSa6IXOBI3NXPv_S2ay

# Yeast AutoOligo CRISPR Helper Instructions
Current version is designed to be used with restricion cloning with pML104 (or similar) plasmid (based on Laughery et al. 2014). User selects gene, amino acid residue number, and desired amino acid change and is provided cloning oligos and repair template sequences.

Instructions
1. Input yeast gene name (common or systematic)
2. Input the amino acid residue # you want to change
3. Input what residue you want to change it to (use single letter amino acid code and *=stop)
4. Click small Run icon below ( ▶ on left of form entry) or can select 'Runtime' menu and 'Run all'
5. Requires login with a Google account.
6. After it runs, you may need to scroll back up to see earlier sgRNA target results, which may be closer to the mutation site and more ideal. (If the python code is made visible, you may need to scroll to very bottom after running to see the results).
7. Manual verification of the outputed sequences is strongly suggested.

Notes:
* Known bugs:
    - sometimes the amino acid alignment is wrong, such as showing stop codons on both aligned sequences suggesting that an incorrect reading frame used in alignment. Presumabably sequences are OK and this is a just a minor alignment issue to be fixed.
    - sometimes some error when making mutations appears as you can see in the repair template alignment with gene that more than just one codon and PAM site appear to get changed. 
* Lowercase on cloning ready sgRNA sequences indicates sequence needed for cloning into pML104 like plasmid
* Lowercase on repair templates indicates amino acid mutation and silent PAM mutation

Changelog

1.03

*   fixed error from  google form residue not being integer.
"""

# @title Yeast AutoOligo CRISPR Helper Form Entry {"run":"auto","vertical-output":true,"form-width":"256px","display-mode":"form"}


!pip install biopython
import requests
import re
from Bio.Seq import Seq  # Use Biopython to handle sequence manipulation
from Bio import pairwise2
from Bio.pairwise2 import format_alignment

gene = input("yeast gene:",)
residue = int(input("residue number:",) )
mutation = input("mutation, use single letter amino acid code:",)

def resolve_gene_name(yeast_gene):
    """Resolve the common or systematic yeast gene name to its Ensembl gene ID."""
    url = f"https://rest.ensembl.org/xrefs/symbol/saccharomyces_cerevisiae/{yeast_gene}?content-type=application/json"
    response = requests.get(url)
    if response.status_code == 200 and len(response.json()) > 0:
        return response.json()[0]['id']  # Return the Ensembl ID (e.g., YBR127C)
    else:
        raise ValueError("Gene not found. Please check the gene name.")

def get_gene_sequence(yeast_gene):
    """Fetch the yeast gene sequence using Ensembl API for the resolved gene ID."""
    url = f"https://rest.ensembl.org/sequence/id/{yeast_gene}?content-type=text/plain"
    response = requests.get(url)
    if response.status_code == 200:
        return response.text.strip()  # Remove any leading/trailing whitespace
    else:
        raise ValueError("Gene sequence not found in database.")

def find_cas9_sites(gene_sequence, amino_acid_position, window=105):
    """Identify Cas9 guide RNA target sites near the amino acid position, on both forward and reverse strands."""
    # Convert amino acid position to nucleotide position
    nucleotide_position = (amino_acid_position - 1) * 3  # Convert to 0-based index and nucleotide position

    # Extract a region of 'window' nucleotides around the amino acid position
    start = max(0, nucleotide_position - window // 2)
    end = min(len(gene_sequence), nucleotide_position + window // 2)
    region = gene_sequence[start:end]

    # Forward strand: look for NGG PAM
    forward_cas9_sites = []
    for m in re.finditer(r'(?=([ACGT]{21}GG))', region):
        pos = start + m.start()
        guide_pam_seq = m.group(1)  # 20 nt guide + 'GG' PAM
        forward_cas9_sites.append((pos, guide_pam_seq, 'forward'))

    # Reverse strand: look for CCN PAM (corresponds to NGG on reverse complement)
    reverse_cas9_sites = []
    for m in re.finditer(r'(?=(CC[ACGT]{21}))', region):
        pos = start + m.start()
        guide_pam_seq = m.group(1)  # 'CC' PAM + 20 nt guide
        reverse_cas9_sites.append((pos, guide_pam_seq, 'reverse'))

    # Combine and sort
    all_cas9_sites = forward_cas9_sites + reverse_cas9_sites
    cas9_sites_sorted = sorted(all_cas9_sites, key=lambda site: abs(site[0] - nucleotide_position))
    return cas9_sites_sorted

def codon_to_amino_acid(codon):
    """Return the amino acid corresponding to the codon."""
    codon = codon.upper()
    for amino_acid, codons in codon_table.items():
        if codon in codons:
            return amino_acid
    return None

def generate_repair_template(gene_sequence, cas9_site, amino_acid_position, new_amino_acid):
    """Create a repair template with the mutation centered as much as possible, ensuring a silent mutation in the PAM."""
    # Convert amino acid position to nucleotide position
    mutation_position = (amino_acid_position - 1) * 3

    # Set the minimum flanking distance
    min_flanking_length = 30

    # Determine the start and end of the repair template
    cas9_cut_position = cas9_site[0] + 17  # Cas9 cuts 3 bp upstream of PAM
    pam_start = cas9_site[0]  # PAM position

    # Ensure the repair template has at least 30 nt on both sides of both mutations
    homology_start = max(0, min(cas9_cut_position, mutation_position) - min_flanking_length)
    homology_end = min(len(gene_sequence), max(cas9_cut_position, mutation_position) + min_flanking_length)
    homology_region = gene_sequence[homology_start:homology_end]

    # Convert to a list for easy mutation
    homology_list = list(homology_region)

    # Apply the desired missense mutation
    codon_start_in_homology = mutation_position - homology_start
    original_codon = ''.join(homology_list[codon_start_in_homology:codon_start_in_homology+3]).upper()
    new_codon_options = codon_table.get(new_amino_acid.upper(), [])
    if not new_codon_options:
        print(f"Error: Invalid amino acid '{new_amino_acid}'.")
        return None, None, None, None
    # Use a codon different from the original codon to indicate mutation
    for codon_option in new_codon_options:
        if codon_option != original_codon:
            new_codon = codon_option.lower()
            break
    else:
        # If all codons are the same as the original, use the first one
        new_codon = new_codon_options[0].lower()
    for i in range(3):
        homology_list[codon_start_in_homology + i] = new_codon[i]

    # Apply silent mutation to the PAM site
    homology_list, silent_mutation_applied = mutate_pam(homology_list, cas9_site[1], cas9_site[2], pam_start, homology_start, codon_table)

    if not silent_mutation_applied:
        # If silent mutation is not possible, return None to indicate skipping this sgRNA
        return None, None, None, None

    # Convert the list back to a string
    mutated_homology = ''.join(homology_list)

    # Generate reverse complement while preserving case
    repair_seq = Seq(mutated_homology)
    reverse_complement = repair_seq.reverse_complement()

    # Extract the corresponding region from the original gene sequence
    original_homology_region = gene_sequence[homology_start:homology_end]

    return mutated_homology, str(reverse_complement), original_homology_region, homology_start

def mutate_pam(homology_list, guide_pam_seq, strand, pam_start, homology_start, codon_table):
    """Ensure that the mutation only targets the PAM site (GG for forward or CC for reverse strand) with silent mutations."""
    # Calculate the position of the PAM in the homology region
    pam_pos_in_homology = pam_start - homology_start

    # For the forward strand, PAM is at positions 20 and 21 in the guide_pam_seq (indexes 20 and 21)
    # For the reverse strand, PAM is at positions 0 and 1 in the guide_pam_seq (indexes 0 and 1)
    if strand == 'forward':
        pam_indices = [pam_pos_in_homology + 20, pam_pos_in_homology + 21]
    else:
        pam_indices = [pam_pos_in_homology, pam_pos_in_homology + 1]

    mutated = False

    # Identify the codon(s) overlapping the PAM site
    codon_positions = set()
    for idx in pam_indices:
        codon_start = (idx // 3) * 3
        codon_positions.add(codon_start)

    for codon_start in codon_positions:
        # Extract the original codon
        codon = ''.join(homology_list[codon_start:codon_start+3])
        amino_acid = codon_to_amino_acid(codon.upper())
        if amino_acid is None or amino_acid == 'STOP':
            continue  # Skip if codon is not valid or is a stop codon

        # Get all synonymous codons for this amino acid
        synonymous_codons = codon_table[amino_acid]

        # Try to find a synonymous codon that has mutations at the PAM site nucleotides
        for syn_codon in synonymous_codons:
            syn_codon = syn_codon.upper()
            differences = [i for i in range(3) if syn_codon[i] != codon[i].upper()]
            # Check if the differences include at least one of the PAM nucleotides
            pam_positions_in_codon = [idx - codon_start for idx in pam_indices if codon_start <= idx < codon_start + 3]
            if any(pos in differences for pos in pam_positions_in_codon):
                # Apply the synonymous codon
                for i in range(3):
                    homology_list[codon_start + i] = syn_codon[i].lower() if syn_codon[i] != codon[i].upper() else syn_codon[i]
                mutated = True
                break  # Stop after finding one valid synonymous codon

    return homology_list, mutated

def main():
    # Input variables (can be adjusted for user input)
    gene_name =   gene # Example gene adjusted for GoogleColab Form, was input("yeast gene: ")
    amino_acid_number = residue # Amino acid residue number, adj for GColab, was int(input("amino acid residue#: ",))
    desired_aa = mutation # Desired mutation (L) adj for googlecolab, was input("amino acid change (one letter code):",)

    # Global codon_table variable
    global codon_table
    codon_table = {
        'F': ['TTT', 'TTC'],
        'L': ['TTA', 'TTG', 'CTT', 'CTC', 'CTA', 'CTG'],
        'I': ['ATT', 'ATC', 'ATA'],
        'M': ['ATG'],
        'V': ['GTT', 'GTC', 'GTA', 'GTG'],
        'S': ['TCT', 'TCC', 'TCA', 'TCG', 'AGT', 'AGC'],
        'P': ['CCT', 'CCC', 'CCA', 'CCG'],
        'T': ['ACT', 'ACC', 'ACA', 'ACG'],
        'A': ['GCT', 'GCC', 'GCA', 'GCG'],
        'Y': ['TAT', 'TAC'],
        'H': ['CAT', 'CAC'],
        'Q': ['CAA', 'CAG'],
        'N': ['AAT', 'AAC'],
        'K': ['AAA', 'AAG'],
        'D': ['GAT', 'GAC'],
        'E': ['GAA', 'GAG'],
        'C': ['TGT', 'TGC'],
        'R': ['CGT', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'],
        'G': ['GGT', 'GGC', 'GGA', 'GGG'],
        'W': ['TGG'],
        '*': ['TAA', 'TAG', 'TGA'],
    }

    # Step 1: Resolve gene name
    try:
        resolved_gene_name = resolve_gene_name(gene_name)
        print("Gene:", gene_name, "resolved as:", resolved_gene_name)
    except ValueError as e:
        print(e)
        return

    # Step 2: Fetch the gene sequence
    gene_seq = get_gene_sequence(resolved_gene_name)

    # Step 3: Find Cas9 target sites near the amino_acid_position
    cas9_sites = find_cas9_sites(gene_seq, amino_acid_number, window=105)

    if not cas9_sites:
        print("No nearby Cas9 target sites found.")
        return

    # Step 4: Generate repair templates for each selected Cas9 site
    repair_templates = []
    for idx, site in enumerate(cas9_sites):
        try:
            repair_template, reverse_complement, original_region, homology_start = generate_repair_template(gene_seq, site, amino_acid_number, desired_aa)
            if repair_template is None:
                continue  # Skip this sgRNA if no valid repair template found
            repair_templates.append((site, repair_template, reverse_complement, original_region, homology_start))
        except ValueError as e:
            print(f"Error for sgRNA {idx + 1}: {e}")
            continue

    if not repair_templates:
        print("No sgRNAs available with silent PAM mutations.")
        return

    # Step 5: Display all found guide RNAs and corresponding repair templates
    for idx, (site, template, rev_comp, original_region, homology_start) in enumerate(repair_templates):
        if site[2] == 'reverse':
            # For reverse strand, reverse complement the guide_pam_seq to get sgRNA sequence ending with NGG
            sgRNA_seq = str(Seq(site[1]).reverse_complement())
        else:
            sgRNA_seq = site[1]  # Forward strand, guide RNA with PAM at 3'

        # Ensure sgRNA ends with NGG or starts with CCN
        if not (sgRNA_seq.endswith('GG') or sgRNA_seq.startswith('CC')):
            print(f"Warning: sgRNA {idx + 1} does not end with NGG or start with CCN.")

        # Remove the PAM for the modified sgRNA
        modified_sgRNA_seq = sgRNA_seq[:-3] if sgRNA_seq.endswith('GG') else sgRNA_seq[3:]  # Remove PAM

        # Add cloning sequences
        modified_sgRNA = 'gatc' + modified_sgRNA_seq + 'GTTTTAGAGCTAG'.lower()
        modified_sgRNA_rev_comp = 'ctagctctaaaac' + str(Seq(modified_sgRNA_seq).reverse_complement())

        strand_direction = "forward" if site[2] == 'forward' else "reverse"
        print(f"\nsgRNA {idx + 1}: {sgRNA_seq} (Strand: {strand_direction}, Position in gene: {site[0]})")
        print(f"pML104 cloning Oligo{idx + 1}A: {modified_sgRNA}")
        print(f"pML104 cloning Oligo{idx + 1}B: {modified_sgRNA_rev_comp}")
        print(f"RepairTemplate Oligo{idx + 1}A: {template}")
        print(f"RepairTemplate Oligo{idx + 1}B: {rev_comp}")

        # Perform sequence alignment between the original region and the repair template without gaps
        print("\nSequence Alignment between Gene and Repair Template:")
        # Define match and mismatch scores
        match_score = 2
        mismatch_score = -1
        # Set gap penalties to very negative values to disallow gaps
        gap_open_penalty = -1000
        gap_extend_penalty = -1000

        alignments = pairwise2.align.globalms(original_region.upper(), template.upper(), match_score, mismatch_score, gap_open_penalty, gap_extend_penalty)
        # Display the best alignment
        alignment = alignments[0]
        print(format_alignment(*alignment))

        # Translate the original and repaired sequences
        original_protein = Seq(original_region).translate()
        repaired_protein = Seq(template).translate()

        # Perform amino acid sequence alignment without gaps
        print("Partial Amino Acid Alignment:")
        aa_alignments = pairwise2.align.globalms(str(original_protein), str(repaired_protein), match_score, mismatch_score, gap_open_penalty, gap_extend_penalty)
        aa_alignment = aa_alignments[0]
        print(format_alignment(*aa_alignment))

if __name__ == "__main__":
    main()
